name = "Re:Create Public SMP"
author = "codeN"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d226819824be5cf17d27536a971ad1a0bb3656cb339e1d75fe8efc45706ad2b8"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
