name = "Re:Create Public SMP"
author = "codeN"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9221398890d7b2dc45fce140e2db40e5f2a1e158eb84313f991f5638cba742b"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
