name = "Re:Create Public SMP"
author = "codeN"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad94ff2ddad4d05194e220cb78f38b394bdfef78c8cca0cfeece59848908df4f"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
