name = "Re:Create Public SMP"
author = "codeN"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07788c2b0f1947270afe4cfd1214c11f55e2674dc56dab5a776f40c77e0c06c1"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
